### PR TITLE
Fix/ios build

### PR DESCRIPTION
**Pull request by salvatoto**
### Main issues resolved:
- Add "staticlib" to cargo.toml to build static libraries for xcframework
- But then need to build dynamic framework in podspec so we can pass path to BoltzCore.init() in consuming project
- Removed bindings.h - I think this was an old ffe file? Conflicted with frb_generated.h
- The last commit,`Copy ios binary to ios dir`, perhaps you want to handle differently. Just need to copy the built framework from rust/target to ios dir

### Instructions when adding to Flutter project:
1. In the flutter_rust_bridge Dart wrapper, we need to point to the pod framework, which will contain the rust library:

Add this helper in Dart code:
```
final DynamicLibrary _objcLib = DynamicLibrary.process();

class NSBundleHelper {
  static final Pointer<Utf8> Function() _getMainBundlePath = _objcLib
      .lookup<NativeFunction<Pointer<Utf8> Function()>>('getMainBundlePath')
      .asFunction();

  static String get mainBundlePath => _getMainBundlePath().toDartString();
}
```

And this obj-c helper in `NSBundleHelper.h` in iOS Runner project:
```#ifndef NSBundleHelper_h
#define NSBundleHelper_h

// BundleHelper.h

#import <Foundation/Foundation.h>

// Declares the C function for external use.
__attribute__((visibility("default")))
const char* getMainBundlePath(void);

#endif /* NSBundleHelper_h */
```

```
#import <Foundation/Foundation.h>
#import "NSBundleHelper.h"

const char* getMainBundlePath() {
    return [[NSBundle mainBundle].bundlePath UTF8String];
}
```

2. Then point to pod framework for iOS. Android will be able to find the bare rust library `boltzclient`, however, since for iOS we wrap it in a cocoapods xcframework, we can find it this way:
```      final externalLibrary = Platform.isIOS
          ? ExternalLibrary.open(
              '${NSBundleHelper.mainBundlePath}/Frameworks/boltz_dart.framework/boltz_dart')
          : null;
      await BoltzCore.init(externalLibrary: externalLibrary);
```

3. Add bundle helper and frb bindings to `Runner-Bridging-Header.h` in iOS Runner Project:
```#import "NSBundleHelper.h"
#import <boltz_dart/frb_generated.h>
```

34 Add `NSBundleHelper.m` to Xcode > Build Phases > Compile Sources if not there already

5. Add `dummyMethodToEnforceBundling` in ios/AppDelegate. Don't call it, just need to be in that file so those functions aren't stripped during linking

### CODE REVIEW

**Comment by i5hi** [comment]
Thanks for the PR @salvatoto !

The binaries are building correctly. I will merge this and make a release with the mac/ios binaries. 

If there are any issues with using the library following the release we can address it in a new PR.

**Comment by cuhte3** [comment]
Am trying to add it to my native iOS app through SPM dependency and seeking for advices. As far as I can see I could use the C libboltz framework and fed_generated.h interface to create SPM package. The missing part right now is translation of the rust interfaces/types/errors located in rust/src/api/ into swift api. Does that sounds correct flow? Any advice? should I use the dummyMethodToEnforceBundling in my app? Thanks for the awesome library!

**Comment by i5hi** [comment]
Hey @cuhte3! 

I am not familiar with iOS development and would not be able to comment on whether this flow would work. 

AFAIK flutter_rust_bridge (frb) is best suited to translating files from rust to flutter. The flutter code then calls into the shared library binary files compiled in rust for ios. For Swift code, you maybe better served by a library like [uniffi](https://github.com/mozilla/uniffi-rs). 

This is a good reference project: https://github.com/thunderbiscuit/uniffi-bindings-template

You could create a library using the same rust files as boltz-dart/rust and some uniffi macros to generate swift code.

**Comment by i5hi** [comment]
Another good example of a rust project with Swift bindings: https://github.com/Blockstream/lwk/tree/master/lwk_bindings

**Comment by i5hi** [comment]
```
#import <Foundation/Foundation.h>
#import "NSBundleHelper.h"

const char* getMainBundlePath() {
    return [[NSBundle mainBundle].bundlePath UTF8String];
}
```

Where does this go?

**Pull request merged**
